config/routes.rb
Highlights::Application.routes.draw do

  devise_for :users

  root to: 'users#index'
  resources :users do
    resources :highlights
  end
  
end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
  attr_accessible :user_id, :title, :description
  
  belongs_to :user
  
  validates :title, presence: true
  validates :description, presence: true
  
  def to_param
    "#{id} #{title}".parameterize 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :highlights
  
  attr_accessible :name

  validates :name, presence: true
  
  #  Add back if validatable commented out
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates_presence_of :password, on: :create
  # validates_presence_of :password_confirmation, on: :create
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  
                     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_filter :require_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :authorize_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_user
  before_filter :find_highlight, only: [:edit, :update, :show, :destroy]
  
  def index
    @highlights = @user.highlights.all
  end
  
  def new
    @highlight = current_user.highlights.new()
  end
  
  def create
    @highlight = current_user.highlights.create(params[:highlight])
    if @highlight.save
      redirect_to user_highlight_url(@user,@highlight)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @highlight.update_attributes(params[:highlight])
      redirect_to user_highlight_path(@user, @highlight)
    else
      render :edit
    end
  end
  
  def show
  end
  
  def destroy
    @highlight.destroy
  end
  
  private
  
    def authorize_user
      if cannot?
        flash[:error] = 'Not Authorized!'
        redirect_to root_url
      end
    end
    
    def require_user
      if !current_user
        flash[:error] = "You have to be signed in!"
        redirect_to root_url
      end
    end
  
    def cannot?
      current_user.id != params[:user_id].to_i
    end
    
    def find_highlight
      @highlight = @user.highlights.find(params[:id])
    end
    
    def find_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, only: [:edit, :update, :show, :destroy]
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create(params[:user])
    if @user.save
      redirect_to user_url(@user)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      redirect_to user_url(@user)
    else
      render :edit
    end
  end
  
  def show
    @highlights = @user.highlights.all
  end
  
  def destroy
    @user.destroy
  end
  private
    def find_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "danger"
    when :alert then "warning"
    end
  end
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def allowed?(user_id, owner_id)
    me(user_id, owner_id)
  end
  
  
  def me(user_id, owner_id)
    return true if user_id == owner_id
  end
end

app/views/highlights/_error_messages.html.erb
<% if @highlight.errors.any? %>
    <div class="error_messages">
        <div class="alert alert-danger">
            <a class="close" data-dismiss="alert">×</a>
            <h4 class="alert-heading">Warning!</h4>
            <ul>
                <% @highlight.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul> 
        </div><!-- end of alert alert-error-->
    </div><!-- end of error_messages-->
<% end %>

app/views/highlights/_form.html.erb
<div class='row'>
	<div class="col-md-6 col-md-offset-3">
			<%= form_for [@user, @highlight] do |f|%>
			<div class='form-group'>
				<%= render 'error_messages' %>
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control' %>
			</div>

			<div class='form-group'>
				<%= f.label :description %>
				<%= f.text_area :description, class: 'form-control' %>
			</div>
		
			<div class='form-group'>
				<%= f.submit class: 'btn btn-primary btn-large' %>
				<%= link_to 'Cancel', user_highlights_path(current_user), class: 'btn btn-danger btn-large' %>		
			</div>
			<% end %>

	</div>	
</div>

app/views/highlights/edit.html.erb
<%= render 'form' %>

app/views/highlights/index.html.erb
<div class='row'>
	<div class='col-md-12'>
		<h1><%= @user.name.titlecase.possessive %> Highlights</h1>
	</div>
	<div class='col-md-4 col-md-offset-3'>
		
			<% if current_user && allowed?(current_user.id, @user.id) %>
			<h3>Create a new highlight! 
				<%= link_to"<span class='glyphicon glyphicon-plus'></span>".html_safe, new_user_highlight_path(current_user) %>
			</h3>
			<% end %>
		
	</div>
	<div class='col-md-6 col-md-offset-3'>
		<div class='row'>
			<% @highlights.each do |highlight| %>
				<div class='col-md-2'>
					<%= link_to "View", user_highlight_path(@user, highlight), class: 'btn btn-large btn-primary' %>	
				</div>				


				<div class='col-md-4'>
					<h5>Title: <span><%= highlight.title %><span></h5> 
				</div>
				<div class='col-md-6'>
					<h5>Description: <span><%= highlight.description %></span></h5>
				</div>
			<% end %>
		</div>	
	</div>
	<div class='col-md-6 col-md-offset-3'>
		<%= link_to "Back to users", users_path, class: 'btn btn-success' %>
	</div>
</div>

app/views/highlights/new.html.erb
<%= render 'form' %>

app/views/highlights/show.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h3><%= @highlight.title %></h3>
	</div>
	<div class='col-md-6 col-md-offset-3'>
		<p><%= @highlight.description %></p>
	</div>
	<div class='col-md-6 col-md-offset-3'>
		<% if current_user && allowed?(current_user.id, @user.id) %>
			<%= link_to 'Edit', edit_user_highlight_path(@highlight), class: 'btn btn-primary btn-large' %>		
		<% end %>
		<%= link_to 'See All Highlights', user_highlights_path(@user), class: 'btn btn-success btn-large' %>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <div>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Highlight</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Users', users_path %></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to "Signed in as #{current_user.email}", edit_user_registration_path(@user) %></li>
				<% end %>
				<% unless user_signed_in? %>
					<li><%= link_to "Sign up!", new_user_registration_path %></li>				
				<% end %>

				<% if user_signed_in? %>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
				<% else %>	
					<li class='active'><%= link_to "Sign in", new_user_session_path %></li>
				<% end %>
          </ul>
        </div><!--/.nav-collapse -->
        </div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Highlights</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class='container'>
	<%= render 'shared/flash_messages' %>
	<%= yield %>
</div>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-<%= flash_class(level) %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user_path%> | <%= user.email user_path %>
</li>

app/views/users/index.html.erb
<div class='row'>
	<div class='col-md-12'><h1>Users</h1></div>
	<div class='col-md-6 col-md-offset-3'>
		<div class='row'>
			<% @users.each do |user| %>
				<div class='col-md-2'>
					<%# if current_user && allowed(current_user, highlight.user_id) %>
						<%= link_to "View", user_path(user), class: 'btn btn-primary' %>
					<%#end %>
				</div>
				<div class='col-md-4'>
					<h5>Name: <span><%= user.name %><span></h5> 
				</div>
				<div class='col-md-6'>
					<h5>Email: <span><%= user.email %></span></h5>
				</div>
			<% end %>
		</div>
			
	</div>
</div>

app/views/users/show.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h3><%= @user.name.titlecase.possessive %> user page</h3>
	</div>
	<div class='col-md-6 col-md-offset-3'>
		<h3>Check out all the highlights</h3>
		<%= link_to 'See Highlights', user_highlights_path(@user), class: 'btn btn-large btn-primary' %>
	</div>
</div>